decode_charset: UTF-8

server:
  port: 8090

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


CMPP:
  ServerIp: "127.0.0.1"
  ServerPort: 7891
  ServiceCode: "09997"
  CompanyCode: "901236"
  BusinessCode: "901861"
  Pwd: "1236"
  ReCount: 3